Console.Write("Nome del libro: ");
string bookTitle = Console.ReadLine();
Console.Write("Autore del libro: ");
string bookAuthor = Console.ReadLine();
Console.Write("ISBN Code: ");
string bookIsbnCode = Console.ReadLine();
Console.Write("Numero di pagine: ");
uint pageNumber = uint.Parse(Console.ReadLine());
Console.Write("Peso del libro: ");
float bookWeight = float.Parse(Console.ReadLine());
Console.Write("Larghezza del libro: ");
double bookWidth = double.Parse(Console.ReadLine());
Console.Write("Spessore del libro: ");
double bookThickness = double.Parse(Console.ReadLine());
Console.Write("Altezza del libro: ");
double bookHeigth = double.Parse(Console.ReadLine());
Console.Write("Rating del libro: ");
string bookRating = Console.ReadLine();
Console.Write("Numero di recensioni del libro: ");
uint bookReviews = uint.Parse(Console.ReadLine());
Console.Write("Kindle? ");
bool isBookAvailableOnKindle = bool.Parse(Console.ReadLine());
Console.Write("Copertina Flessibile? ");
bool isCoverFlexible = bool.Parse(Console.ReadLine());

Console.WriteLine($"-------- IL LIBRO DI OGGI: {bookTitle} di {bookAuthor} ------------");
Console.WriteLine("Informazioni generiche:");
Console.WriteLine($"ISBN: {bookIsbnCode}");
Console.WriteLine($"Numero delle pagine : {pageNumber}");
Console.WriteLine($"Dimensioni del libro: {bookWidth} x {bookThickness} x {bookHeigth} cm");
Console.WriteLine();
Console.WriteLine($"Informazioni Amazon:");
Console.WriteLine($"Numero Recensioni: {bookReviews}");
Console.WriteLine($"Valutazione Media: {bookRating} stelline");
Console.WriteLine($"Kindle Disponibile: {isBookAvailableOnKindle}");
Console.WriteLine($"Copertina flessibile disponibile: {isCoverFlexible}");
Console.WriteLine("----------------------------------------------------------------------------");
